# Generated by Django 5.1.1 on 2024-10-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='quiz.questions'),
        ),
    ]
